name: mingleve
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^1.0.3
  carousel_slider: ^5.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  intl_phone_number_input: ^0.7.4
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  flutter_native_splash: ^2.4.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Path to your logo image

flutter:
  uses-material-design: true

  assets:
    - assets/photo1.jpg
    - assets/photo2.jpg
    - assets/photo3.jpg
    - assets/drawer_background.png
    - assets/logo.png
    - assets/rave_party.jpg
    - assets/masquerade_party.jpg
    - assets/pool_party.jpg
    - assets/sundowner.jpg
    - assets/house_party.jpg
    - assets/profile_pic.jpg
    - assets/prom_night.jpg
    - assets/weekend_bash.png
    - assets/birthday_celebrations.png
    - assets/holiday_trips.png
    - assets/club_nights.png
    - assets/festivals.png

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/logo.png # Path to your logo image
  android: true
  ios: true

